<?php
declare(strict_types=1);

/**
 * WordPress integration bootstrap.
 *
 * Requirements:
 * - WP test library installed (default: /tmp/wordpress-tests-lib)
 * - WP test config generated by install-wp-tests.sh
 */
$tests_dir = getenv('WP_TESTS_DIR');
if (!$tests_dir) {
    $vendor_tests_dir = dirname(__DIR__, 2) . '/vendor/wp-phpunit/wp-phpunit';
    $tests_dir = file_exists($vendor_tests_dir . '/includes/functions.php')
        ? $vendor_tests_dir
        : '/tmp/wordpress-tests-lib';
}

if (!file_exists($tests_dir . '/includes/functions.php')) {
    fwrite(STDERR, "WordPress test library not found at {$tests_dir}.\n");
    fwrite(STDERR, "Install it first with ./tools/install-wp-tests.sh <db_name> <db_user> <db_pass> [db_host] [wp_version].\n");
    exit(1);
}

require_once $tests_dir . '/includes/functions.php';

function _can_load_plugin_for_tests(): void {
    require dirname(__DIR__, 2) . '/circular-arts-network.php';
}
tests_add_filter('muplugins_loaded', '_can_load_plugin_for_tests');

require $tests_dir . '/includes/bootstrap.php';
